### ISSUE TITLE
Files renamed by Sonarr are not handled by Greyhole (until fsck)

### ISSUE THREAD

**Issue by jancoow** [gboudreau/Greyhole#220]
Hi,

I've a strange problem where for some reason files in the /shares folder are not symbolic linked to any of my greyhole storage pool drive. This means it is accessible by the samba share, but it's not actually on the greyhole storage pool. How can I fix this? It are around 60 files. 

I've encountered this problem after I was having this issue:

I wanted to balance my greyhole installation a bit, because one of the drives is also my download directory. I needed to move some files of it, and because it was -250gb according the balance page, I figured out a quick re-balance would fix that. However, it won't do the drive first with the least space, so I wanted it to cancel after 10 minutes. However, greyhole --cancel-balance didn't work and I saw the spooled files still counting up in the greyhole --view-queue command. At that point I restarted greyhole with systemctl. 

After restarting it I got some strange log messages about these files:

```
  Mar 24 15:53:29 DEBUG read_smb_spool: File pointer to path/to/file was closed without being written to. Ignoring.
  Mar 24 15:53:29 DEBUG read_smb_spool: File pointer to path/to/file2 was closed without being written to. Ignoring.
  Mar 24 15:53:29 DEBUG read_smb_spool: File pointer to path/to/file3 was closed without being written to. Ignoring.
  Mar 24 15:53:29 DEBUG read_smb_spool: File pointer to path/to/file4 was closed without being written to. Ignoring.
```

At this point I checked which files are not symlinked with 
`find shares/ -type f `
Which resulted in 60 files.

**Comment by gboudreau** [comment]
You can use `greyhole --fsck --dir=/path/to/share --email-report`

**Comment by jancoow** [comment]
Thanks that seems to fixed it! Any explanation why this happened? Most of the files were files which I was moving to a same share right at the moment of the balance. But there were also ~20 files much older and already a long time in my shares.

**Comment by jancoow** [comment]
It seems like that after a few days newly added files won't be moved to any storage drive, while greyhole --status is saying:

Currently idle.

Recent log entries:
  Mar 27 11:00:50 DEBUG read_smb_spool: Processing Samba spool...
  Mar 27 11:00:50 DEBUG sleep: Nothing to do... Sleeping.

**Comment by gboudreau** [comment]
Are you able to reproduce this issue consistently ? i.e. if you create a new text file on your shares, and check the greyhole.log file, you donèt see that file being processed?

If so, do this after creating your test file:
https://github.com/gboudreau/Greyhole/wiki/GetHelp#gather-system-information

Also, include in your response the command you used to test. Some like
```
$ echo 1 > /mnt/samba/share_name/file1
$
```

**Comment by jancoow** [comment]
Weird, I'm not able to reproduce it with creating or editing a file. It seems only to be happening with some docker application moving files to a locally mounted samba share.

**Comment by jancoow** [comment]
So I've managed to see the situation. My docker application moves a file from my ssd to the samba share with an extension .mkv.partial~, then renames it to .mkv . This seems to be going wrong:


```
Mar 30 11:54:55 DEBUG sleep: Nothing to do... Sleeping.
Mar 30 11:54:55 DEBUG sleep: Nothing to do... Sleeping.
Mar 30 11:55:05 DEBUG sleep: Nothing to do... Sleeping.
Mar 30 11:55:15 DEBUG read_smb_spool: Processing Samba spool...
Mar 30 11:55:17 DEBUG read_smb_spool: Found 1 new tasks in spool.
Mar 30 11:55:17 INFO write: Now working on task ID 9606569: write /path/to/file.mkv.partial~
Mar 30 11:55:17 DEBUG write:   File is still being written to (212MB). Postponing.
Mar 30 11:55:17 DEBUG read_smb_spool: Processing Samba spool...
Mar 30 11:55:21 DEBUG sleep: Nothing to do... Sleeping.
Mar 30 11:55:31 DEBUG read_smb_spool: Processing Samba spool...
Mar 30 11:55:31 INFO write: Now working on task ID 9606569: write /path/to/file.mkv.partial~
Mar 30 11:55:31 DEBUG write:   File is still being written to (798MB). Postponing.
Mar 30 11:55:31 DEBUG read_smb_spool: Processing Samba spool...
Mar 30 11:55:33 DEBUG sleep: Nothing to do... Sleeping.
Mar 30 11:55:43 DEBUG read_smb_spool: Processing Samba spool...
Mar 30 11:55:44 INFO write: Now working on task ID 9606569: write /path/to/file.mkv.partial~
Mar 30 11:55:44 DEBUG write:   File is still being written to (1.26GB). Postponing.
Mar 30 11:55:44 DEBUG read_smb_spool: Processing Samba spool...
Mar 30 11:55:45 DEBUG sleep: Nothing to do... Sleeping.
Mar 30 11:55:55 DEBUG read_smb_spool: Processing Samba spool...
Mar 30 11:55:56 INFO write: Now working on task ID 9606569: write /path/to/file.mkv.partial~
Mar 30 11:55:56 DEBUG write:   File is still being written to (1.69GB). Postponing.
Mar 30 11:55:56 DEBUG read_smb_spool: Processing Samba spool...
Mar 30 11:55:56 DEBUG sleep: Nothing to do... Sleeping.
Mar 30 11:56:06 DEBUG read_smb_spool: Processing Samba spool...
Mar 30 11:56:06 INFO write: Now working on task ID 9606569: write /path/to/file.mkv.partial~
Mar 30 11:56:06 DEBUG write:   File is still being written to (2.10GB). Postponing.
Mar 30 11:56:06 DEBUG read_smb_spool: Processing Samba spool...
Mar 30 11:56:06 DEBUG sleep: Nothing to do... Sleeping.
Mar 30 11:56:16 DEBUG read_smb_spool: Processing Samba spool...
Mar 30 11:56:16 DEBUG read_smb_spool: Found 3 new tasks in spool.
Mar 30 11:56:16 INFO write: Now working on task ID 9606569: write /path/to/file.mkv.partial~
Mar 30 11:56:16 INFO write: /mnt/hdd1/shares//path/to/file.mkv.partial~ doesn't exist anymore.
Mar 30 11:56:16 INFO write:   Skipping.
// removed a few lines which has nothing to do with this problem 
Mar 30 11:56:17 INFO unlink: Now working on task ID 9606572: unlink /path/to/file.mkv.partial~
Mar 30 11:56:17 INFO unlink: File deleted: /mnt/hdd1/shares//path/to/file.mkv.partial~
Mar 30 11:56:17 DEBUG unlink: Loading metafiles for /path/to/file.mkv.partial~ ...
Mar 30 11:56:17 DEBUG unlink:   Got 0 metadata files.
Mar 30 11:56:17 DEBUG unlink:   Removing metadata files for /path/to/file.mkv.partial~
Mar 30 11:56:17 DEBUG sleep: Nothing to do... Sleeping.
Mar 30 11:56:27 DEBUG read_smb_spool: Processing Samba spool...
Mar 30 11:56:27 DEBUG sleep: Nothing to do... Sleeping.
Mar 30 11:56:37 DEBUG read_smb_spool: Processing Samba spool...
Mar 30 11:56:37 DEBUG sleep: Nothing to do... Sleeping.
```

So apparently a move with directly a rename isn't captured properly?

**Comment by gboudreau** [comment]
Pretty positive the case you mention is supported; I use it and see it all the time on my fileserver.

Are you sure the target directory (the path where the file ends up, in .mkv) is in your locally mounted shares? With the log you provided, it would seem the .partial~ file is written in your shares, but the file is then moved somewhere else, which means the .partial~ file is simply deleted, because the .mkv is gone somewhere else.  
Even if the .mkv ends up in the same folder, the software that does that rename might be doing something like:

```
mv /mnt/samba/Videos/file1.mkv.partial~ /path/to/lz/Videos/file1.mkv
```

That operation indeed be invisible to Greyhole.
Maybe check your software logs, or enable more verbose (debugging) logs, to be able to see the exact operations or commands it runs, to rename the complete file.

What is that software? Maybe I can try it on my side, confirms if the way it renames the final file is indeed problematic for Greyhole, or not.

**Comment by jancoow** [comment]
Yes it's weird, It has been working for a long time but I think after the last update of greyhole I got this issue (but I'm not sure). Could be the latest smb update as well. I'm using sonarr to move files from my torrent client to the samba share. I'm 100% sure it is moved correctly to the samba share (otherwise the .partial~ file wouldn't be created in the locally mounted share either).

**Comment by gboudreau** [comment]
I'm using Sonarr too (version 2.0.0.5344); never had issues.  
I'm using the latest Greyhole (0.12.0) and Samba 4.10.
You?

What you could try:
- Change Sonarr Settings > General > Logging > Log Level: Trace
- Stop the greyhole daemon just before a file gets renamed by Sonarr.
(In the logs above, that would mean you should stop it between 11:56:06 and 11:56:16. Stop it earlier than that, if you're unsure.)

Then:
```
tar zcf ~/greyhole-samba-spool.tgz /var/spool/greyhole/
```

Send me the resulting `~/greyhole-samba-spool.tgz`, and the `Sonarr.trace.txt` files to guillaume@greyhole.net
I'll check in there to see if I can see something wrong in the spool operations logged by the Samba VFS module. My guess: the rename operation is not logged, for some reason.

**Comment by jancoow** [comment]
**Sonar**: 2.0.0.5344
**Greyhole** 0.11.1
**Samba**:  4.7.6-Ubuntu
**smbd**: 4.7.6-Ubuntu

As you can see I'm running a quite newer samba version and a bit older greyhole one. 

I'll try to setup the debug tools tonight.

**Comment by gboudreau** [comment]
Couldn't find anything relevant in your spool folder.  
Folder (`Season 3`) is created at 22:04:04.609857; then `.partial~` starts being written to at 22:04:04.863117, until 22:04:16.873277, when the file handle is closed (the writing is complete). That folder doesn't contain a `rename` or `unlink` operation...

You can watch your spool folder with this :
```
curl -O https://gist.githubusercontent.com/gboudreau/bf3cd0b3fac1ad62b3244014c44649af/raw/greyhole-spool-debugger.php
while true; do php greyhole-spool-debugger.php /var/spool/greyhole; sleep 1; done
```

Of note: the spool files will appear as soon as the operation can be logged by Samba, but if the greyhole daemon is running, it can consume the spooled files before the script can read them. Thus why you should shut down the greyhole daemon while debugging this.

**Comment by gboudreau** [comment]
In Sonarr: Settings > Media management > Advanced Settings: Shown > Use Hardlinks instead of Copy: is this set to Yes or No? (Should be No.)
If it was set to Yes, toggle it, and try again.

**Comment by gboudreau** [comment]
Also, I created a 0.12.1 version of Greyhole that should resolve this; it adds support for hard-links on Greyhole shares. Let me know.

**Comment by jancoow** [comment]
> In Sonarr: Settings > Media management > Advanced Settings: Shown > Use Hardlinks instead of Copy: is this set to Yes or No? (Should be No.)
> If it was set to Yes, toggle it, and try again.

This was indeed set to true. That must be the issue! However I cannot remember that I changed this lately. 

What is this hardlink exactly, and why doesn't it work with greyhole?

**Comment by gboudreau** [comment]
> This was indeed set to true. That must be the issue! However I cannot remember that I changed this lately.

It is enabled by default. So this was always an issue. But the problem would sometimes not be visible to the end-user, because Sonarr will retry different ways of moving/copying the file, if one fails, and so sometimes, using hard-links would fail, and Sonarr would fall-back to using a normal "mv" or "cp" command to move/copy the file. And that, Greyhole handles just fine.

> What is this hardlink exactly, and why doesn't it work with greyhole?

The Greyhole VFS module simply never implemented logging for the creation of hard links. So those file operations were simply invisible to Greyhole. Why : because "normally", you can't create hard links on your Greyhole shares. If you try to create a hard link of a random file on your shares right now, you'll get:

```
gb@fileserver4:/mnt/samba/Videos $ ln file1 file2
ln: failed to create hard link 'file2' => 'file1': Permission denied
```

But, there is a small window (or not so small, when the file is large enough, or the Greyhole daemon has a backlog of tasks to process) during which you CAN create hard links: before Greyhole has time to move the file from the LZ to a storage pool drive.

```
gb@fileserver4:/mnt/samba/Videos $ echo 1 > file1 ; ln file1 file2
```

Greyhole 0.12.1 fixes that; I added logging for hard links creation, and Greyhole now handles those the same as regular "write" operations.

FYI Hard links are this:
![image](https://user-images.githubusercontent.com/370329/78023686-1619df80-7325-11ea-9a42-27455b220ad3.png)

Just two different filenames that are actually pointing to the same data on the disk.

Compared to a symlink (symbolic link):
![image](https://user-images.githubusercontent.com/370329/78023918-8163b180-7325-11ea-84e1-678955c44e7a.png)

A symbolic link is: Link B should refer to the same thing as Link A; i.e. if Link A is deleted, Link B will be broken, and the data (on disk) will be effectively deleted (nothing point to it anymore; any new file could use that space now).
Versus for hard links, where even if Link A gets deleted, Link B will still continue to work as expected, and no actual data will be deleted.

If you'd like, keep that Hard Link setting to Yes in Sonarr, and upgrade your Greyhole to 0.12.1+, and let me know if it resolves your issue.

**Comment by jancoow** [comment]
Right, got it. Thanks for the explanation. I didn't know that a hardlink could exist over a samba share in the first place. However, after disabling the hard links in sonarr, I still see moved files by sonar not picked up by greyhole. So it doesn't seem to be fixed. This is on the old version of greyhole, so I'll try to update it now and see if it fixes it.

**Comment by jancoow** [comment]
And again, files moved by sonar are not detected. Weird behaviour! I'll try to turn hard links on again and see if that makes any difference.

I can't really remember what changed last time. The only thing what could be is that I updated greyhole and samba. Maybe this samba version is not compatible with greyhole?

**Comment by gboudreau** [comment]
Try again to create a trace log in Sonarr.
Enable Trace log level (don't forget to hit Save in top-right), then go in any show, and try to download an old episode you don't have (manually; pick one version that is small enough, so that it doesn't take long to download). Wait until Sonarr finishes moving the episode into the right folder.
Send me the trace log, and the greyhole logs for the same period (and a little longer, to ensure it had time to process the last Sonarr files operations).

**Comment by gboudreau** [comment]
Indeed, the problem doesn't seem to be hard-links, since your download and media folders are not on the same drives! (Hard links only work on the same partition.)

```
20-4-1 17:01:19.8|Debug|DiskTransferService|HardLinkOrCopy [/downloads/complete/file.mkv] > [/media/path/to/file.mkv]
20-4-1 17:01:19.8|Debug|DiskProvider|Hardlink '/downloads/complete/file.mkv' to '/media/path/to/file.mkv' failed.

[v2.0.0.5344] Mono.Unix.UnixIOException: Invalid cross-device link [EXDEV].
  at Mono.Unix.UnixMarshal.ThrowExceptionForLastError () [0x00000] in /build/mono/src/mono/mcs/class/Mono.Posix/Mono.Unix/UnixMarshal.cs:478 
  at Mono.Unix.UnixMarshal.ThrowExceptionForLastErrorIf (System.Int32 retval) [0x00004] in /build/mono/src/mono/mcs/class/Mono.Posix/Mono.Unix/UnixMarshal.cs:491 
  at Mono.Unix.UnixFileSystemInfo.CreateLink (System.String path) [0x0000c] in /build/mono/src/mono/mcs/class/Mono.Posix/Mono.Unix/UnixFileSystemInfo.cs:278 
  at NzbDrone.Mono.Disk.DiskProvider.TryCreateHardLink (System.String source, System.String destination) [0x00013] in C:\BuildAgent\work\5d7581516c0ee5b3\src\NzbDrone.Mono\Disk\DiskProvider.cs:182 
```

Maybe we could use the Samba full-audit VFS to see what Sonarr is doing..?
Edit your smb.conf, and change the `vfs objects` line for your Series share, and add a `full_audit:success` line :

```
vfs objects = full_audit greyhole
full_audit:success = all
```

Restart samba, and check in `/var/log/syslog` (or equivalent) for `smb_audit` lines (there will be a LOT of them; don't forget to disable full_audit once you got the log).
If that works, download something else using Sonarr, and send me the log of what full_audit logged, when the file was moved.

Thanks.

**Comment by jancoow** [comment]
Well, my download folder and share landing zone are actually on the same drive. But it's uploaded through the locally mounted samba shares. This always give me a bit of trouble with large torrents. Because after a download is completed, the file get copied, instead of moved, on the same SSD. Herefor I need to have enough free space to make the copy, where greyhole will eventually move it to any other hard drive. I've many times had a lockup where the finished torrent couldn't be copied to my greyhole share because the ssd was full. Any suggestions how this could be handled a bit better? 

I'll try to log the audits! Hopefully that give us some results.

**Comment by jancoow** [comment]
So I was currently working on creating the audit log. After restarting samba again to disable the audit log, I checked if the downloaded file wasn't moved again. However the file actually was successfully moved out of the landing dir! And now all the files sonar is downloading are moved successfully. Except files which were downloaded before the samba restart. Was this the problem all the time, just restarting samba? I'll keep monitoring to see if it happens again.

**Comment by jancoow** [comment]
I'm unable to reproduce the issue anymore. So I'll close this issue and reopen it if I'm having the same problem!
